services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    environment:
      MOUNT_SOURCE: C:/Users/ooooo/Downloads/istio-1.16-dev
#      HOME: C:/Users/ooooo
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

